version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fwc_postgres
    environment:
      POSTGRES_DB: friends_with_cards
      POSTGRES_USER: fwc_user
      POSTGRES_PASSWORD: fwc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - fwc_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fwc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fwc_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  fwc_network:
    driver: bridge
